# Generated by Django 4.2.1 on 2023-06-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todoitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
