# Generated by Django 4.2.1 on 2023-06-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_rename_value_tag_tag_name_tag_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='todo', to='todo_app.tag'),
        ),
    ]
