# Generated by Django 4.2.1 on 2023-06-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_progressnote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressnote',
            old_name='description',
            new_name='progress_note',
        ),
    ]
